include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.gr.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/util/license.dart
    - lib/generated_plugin_registrant.dart

  errors:
    public_member_api_docs: ignore
    type_annotate_public_apis: ignore
    todo: ignore
    lines_longer_than_80_chars: ignore
    body_might_complete_normally_nullable: ignore

linter:
  rules:
    - directives_ordering
    - prefer_const_constructors
    - prefer_relative_imports
    - prefer_single_quotes
    - use_if_null_to_convert_nulls_to_bools
