global_options:
  freezed:freezed:
    options:
      map:
        map: false
        maybe_map: false
        map_or_null: false
      when:
        when: false
        when_or_null: false
        maybe_when: false
    runs_before:
      - hive_generator:hive_generator
  hive_generator:hive_generator:
    runs_before:
      - json_serializable:json_serializable
