name: Feature request ⭐
description: Suggest an idea for improvement
title: "Feature: <title>"
labels: [enhancement, needs triage]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!

        Before filling an issues, we just want to make sure that this app is just a booru viewer.
        It wasn't mean to be, and will never be a full booru client (that support login, comments, vote score, etc),
        so any suggestion regarding those will be closed, thanks.
  - type: dropdown
    attributes:
      label: Type
      options:
        - Functionality
        - UI improvement
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue
      description: What is the current problem. Why does it require a feature request?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature
      description: Describe your feature in detail. How does it solve the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
