name: CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "fastlane/**"
      - "**.md"
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "fastlane/**"
      - "**.md"

jobs:
  check:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install grinder
        run: dart pub global activate grinder
      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Run code generators
        run: grind gencode genlang
      - name: Check code formatting
        run: grind chkfmt
      - name: Analyze code
        run: grind analyze
      - name: Perform testing
        run: grind unittest
