name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Install derry
        run: flutter pub global activate derry
      - name: Sync
        run: derry sync
      - name: Generate
        run: derry gen all
      - name: Test
        run: derry test all
