name: Testing

on:
  push:
    branches: [main]
    paths-ignore:
      - "fastlane/**"
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "fastlane/**"
      - "**.md"

jobs:
  analysis:
    name: Perform static analysis and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Run code generators
        run: |
          dart run build_runner build --delete-conflicting-outputs
          dart run slang
      - name: Check formatting
        run: find lib -iname '*.dart' -not -iname '*.freezed.dart' -not -iname '*.g.dart' | xargs dart format --output=none --set-exit-if-changed
      - name: Analyze code
        run: flutter analyze
      - name: Perform unit testing
        run: |
          dart run full_coverage
          flutter test --coverage
