name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
      - name: Analyze source
        run: flutter analyze
