name: Testing

on:
  push:
    branches: [main]
    paths-ignore:
      - 'fastlane/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'fastlane/**'

jobs:
  analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run slang
      - run: find lib -iname '*.dart' -not -iname '*.freezed.dart' -not -iname '*.g.dart' | xargs dart format --output=none --set-exit-if-changed
      - run: flutter analyze
